version: '3'

services:
  nodejs:
    build: .
    command: npm run serve
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT:-80}:${PORT:-80}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
    networks:
      - app-network 

  mongo-express:
    image: mongo-express
    restart: always
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
    ports:
      - 8081:8081
    networks:
      - app-network 
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge

volumes:
  db_data: